name: Publish package on NPM

on:
  release:
    types: [created]
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install
    - uses: pnpm/action-setup@v2
      with:
       version: 8.9.1
      run: |
        npm i
    - name: publish
    - uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
        registry-url: "https://registry.npmjs.org"
    - run: npm publish --access=public
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}