name: Publish package on NPM

on:
  release:
    types: [created]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      uses: pnpm/action-setup@v2
      with:
        version: 8.9.1
      run: |
        npm i

    - name: Publish to NPM
      uses: actions/setup-node@v2  # Updated to v2
      with:
        node-version: "lts/*"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm publish --access=public
