name: Publish package on NPM

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        node-version: 18
        registry-url: https://registry.npmjs.org/ 
      - uses: pnpm/action-setup@v2
        with: 
         version: 8.9.1   
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}